id = "floe"
name = "Floe"
version = "0.1.0"
schema_version = 1
description = "Syntax highlighting for the Floe data pipeline DSL"
authors = ["Marshall Beddoe <unmarshal@gmail.com>"]
repository = "https://github.com/unmarshal/floe"

[grammars.floe]
repository = "https://github.com/unmarshal/floe"
path = "tree-sitter-floe"
rev = "1327af8"
